# Replace JAVA_HOME with the right path for your environment

libtailscale.aar: *.go go.mod go.sum
	JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home gomobile bind -target android -androidapi 21 libtailscale