name: Build Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Check out code
      uses: actions/checkout@v3
    - name: Switch to Java 17 # Note: 17 is pre-installed on ubuntu-latest
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: make tailscale-debug.apk
